# 2.2 Sklearn
* 데이터 불러오기
* 2.2.1. 싸이킷-런 데이터 분리
* 2.2.2. 싸이킷-런 지도 학습
* 2.2.3. 싸이킷-런 비지도 학습
* 2.2.4. 싸이킷-런 특징 추출

In [1]:
import sklearn
sklearn.__version__

'0.24.1'

### 데이터 불러오기

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris_dataset = load_iris()
print("iris_dataset key: {}".format(iris_dataset.keys()))

iris_dataset key: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [6]:
print(iris_dataset['data'])
print("shape of data: {}". format(iris_dataset['data'].shape))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [7]:
print(iris_dataset['feature_names'])

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print(iris_dataset['target'])
print(iris_dataset['target_names'])

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
['setosa' 'versicolor' 'virginica']


In [9]:
print(iris_dataset['DESCR'])

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

'DESCR'은 'Description'의 약자로서 해당 데이터에 대한 전체적인 요약 정보를 보여준다.

## 2.2.1. 싸이킷-런 데이터 분리
사이킷런을 이용하면 학습 데이터를 대상으로 학습 데이터와 평가 데이터로 쉽게 나눌 수 있다

In [12]:
from sklearn.model_selection import train_test_split

In [16]:
train_input, test_input, train_label, test_label = train_test_split(iris_dataset['data'],
                                                                    iris_dataset['target'],
                                                                    test_size = 0.25,
                                                                    random_state=42)

In [17]:
print("shape of train_input: {}".format(train_input.shape))
print("shape of test_input: {}".format(test_input.shape))
print("shape of train_label: {}".format(train_label.shape))
print("shape of test_label: {}".format(test_label.shape))

shape of train_input: (112, 4)
shape of test_input: (38, 4)
shape of train_label: (112,)
shape of test_label: (38,)


## 2.2.2. 싸이킷-런 지도 학습

* 지도학습 : 각 데이터에 대해 정답이 있는 경우 각 데이터의 정답을 예측할 수 있게 학습시키는 과정 -> 즉 모델이 예측하는 결과를 각 데이터의 정답과 비교해서 모델을 반복적으로 학습시킨다.

### k-최근접 이웃 분류기 (K-nearest neighbor classifier)

예측하고자 하는 데이터에 대해 가장 가까운 거리에 있는 데이터의 라벨과 같다고 예측하는 방법

이 방법은 데이터에 대한 사전 지식이 없는 경우의 분류에 많이 사용된다
k 값은 예측하고자 하는 데이터와 가까운 몇 개의 데이터를 참고할 것인지를 의미

#### k-최근접 이웃 분류기의 특징
* 데이터에 대한 가정이 없어 단순하다.
* 다목적 분류와 회귀에 좋다.
* 높은 메모리를 요구한다.
* k값이 커지면 계산이 늦어질 수 있다.
* 관련 없는 기능의 데이터 규모에 민감하다

In [24]:
# 분류기 객체를 불러온 뒤 객체에 할당
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [25]:
knn.fit(train_input, train_label)

KNeighborsClassifier(n_neighbors=1)

In [30]:
# 4개의 피처값을 임의로 설정해서 넘파이 배열로 만든다
import numpy as np
new_input = np.array([[6.1, 2.8, 4.7, 1.2]])

In [31]:
# 결과 예측
knn.predict(new_input)

array([1])

In [32]:
# 따로 분리해둔 평가 데이터에 대해 예측하고 그 결과값을 변수에 저장한다
predict_label = knn.predict(test_input)
print(predict_label)

[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0 0 0 1 0 0 2 1
 0]


In [33]:
# 예측한 결과값과 실제 결과값을 비교해서 정확도 측정
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 1.00


## 2.2.3. 싸이킷-런 비지도 학습

* 비지도 학습 : 지도 학습과는 달리 데이터에 대한 정답, 
   *  -> 즉 라벨을 사용하지 않고 만들 수 있는 모델
   * 모델을 통해 문제를 해결하면서 데이터에 대한 정답이 없는 경우 적용

#### k-평균 군집화 (K-means Clustering)
* 군집화란 데이터를 특성에 따라 여러 집단으로 나누는 방법
* k-평균 군집화는 군집화 방법 중 가장 간단하고 널리 사용되는 방법
* 데이터 안에서 대표하는 군집의 중심을 찾는 알고리즘

In [35]:
from sklearn.cluster import KMeans
k_means = KMeans(n_clusters=3)

In [38]:
k_means.fit(train_input)

KMeans(n_clusters=3)

라벨값을 넣지 않고 단순히 데이터 사이의 거리를 이용하여 군집화한 것이기 때문에 바로 붓꽃의 라벨을 예측할 수 없지만 군집화한 k-평균 군집화 모델의 라벨 속성을 확인하면 각 데이터의 라벨을 확인할 수 있다.

In [41]:
k_means.labels_

array([1, 1, 0, 0, 0, 1, 1, 0, 0, 2, 0, 2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 2, 1, 0, 0, 1, 0, 0, 0, 0, 2, 0, 1, 0, 2, 1,
       1, 0, 2, 1, 0, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0,
       2, 1, 2, 2, 1, 0, 0, 0, 2, 2, 1, 2, 0, 2, 0, 0, 0, 1, 0, 0, 1, 0,
       2, 2, 1, 0, 2, 2, 1, 2, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 2])

In [42]:
# 각 군집의 종 확인
print("0 cluster:", train_label[k_means.labels_ == 0])
print("1 cluster:", train_label[k_means.labels_ == 1])
print("2 cluster:", train_label[k_means.labels_ == 2])

0 cluster: [2 1 1 1 2 1 1 1 1 1 2 1 1 1 2 2 2 1 1 1 1 1 2 1 1 1 1 2 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 2 2 1 2 1]
1 cluster: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
2 cluster: [2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 1 2 2 2 2]


In [43]:
# 임의의 새로운 데이터를 만들어서 예측을 진행
import numpy as np
new_input  = np.array([[6.1, 2.8, 4.7, 1.2]])

In [44]:
prediction = k_means.predict(new_input)
print(prediction)

[0]


결과 : 새롭게 정의된 데이터는 0군집에 포함된다고 예측

In [46]:
# 평가데이터를 적용시켜 실제 라벨과 비교해 성능을 측정한다
predict_cluster = k_means.predict(test_input)
print(predict_cluster)

[0 1 2 0 0 1 0 2 0 0 2 1 1 1 1 0 2 0 0 2 1 0 1 2 2 2 2 2 1 1 1 1 0 1 1 0 0
 1]


In [48]:
#  적용시켜 예측한 군집을 각 붓꽃의 종을 의미하는 라벨값으로 다시 바꿔줘야 실제 라벨과 비교해서 성능을 측정할 수 있음
np_arr = np.array(predict_cluster)
np_arr[np_arr==0], np_arr[np_arr==1], np_arr[np_arr==2] = 3, 4, 5
np_arr[np_arr==3] = 1
np_arr[np_arr==4] = 0
np_arr[np_arr==5] = 2
predict_label = np_arr.tolist()
print(predict_label)

[1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0]


각 데이터가 속한 군집의 순서를 실제 붓꽃의 라벨로 변경
* 0번째 군집이 라벨 1 (Versicolour)
* 1번째 군집이 라벨 0 (Setosa)
* 2번째 군집이 라벨 2 (Verginica)

* -> 변경할 때는 임시저장을 위해 군집의 순서값 3,4,5 를 넘파이 배열로 먼저 만들고 군집 3을 1(Versicolour), 군집 4: 0 (Setosa), 군집 5: 2 (Verginica)로 바꿔준다

In [50]:
#실제 라벨과 비교하여 성능 확인
print('test accuracy {:.2f}'.format(np.mean(predict_label == test_label)))

test accuracy 0.95


## 2.2.4. 싸이킷-런 특징 추출
자연어 처리에서 특징 추출이란 텍스트 데이터에서 단어나 문장들을 어떤 특징 값으로 바꿔주는 것을 의미한다. 기존에 문자로 구성되어 있던 데이터를 모델에 적용할 수 있도록 특징을 뽑아 어떤 값으로 바꿔서 수치화한다. 
* CountVectorizer
* TfidfVectorizer
* HashingVectorizer

### CountVectorizer

* 단순히 각 텍스트에서 횟수를 기준으로 특징을 추출하는 방법
* 어떤 단위의 횟수를 셀 것인지는 선택 사항[단어, 문자 하나하나]
1. 문장을 입력받아 단어의 횟수를 측정한 뒤 벡터로 만든다
2. 객체를 만들고 특정 텍스트를 적합( = 횟수를 셀 단어의 목록을 만드는 과정) 
3. 횟수를 기준으로 해당 텍스트를 벡터화

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']

count_vectorizer = CountVectorizer()

In [57]:
# 생성한 객체에 fit 함수를 사용해 데이터를 적용 -> 자동으로 단어사전 생성
count_vectorizer.fit(text_data)
print(count_vectorizer.vocabulary_)

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}


In [58]:
# 데이터를 실제로 벡터화
sentence = [text_data[0]] # ['나는 배가 고프다']
print(count_vectorizer.transform(sentence).toarray())

[[1 0 1 0 0 0 1 0 0 0]]


### TfidfVectorizer
* TF - IDF 라는 특정한 값을 사용해서 텍스트 데이터의 특징을 추출하는 방법
* TF  [Term Frequency] : 특정 단어가 하나의 데이터 안에서 등장하는 횟수를 의미한다.
* DF [Document Frequency] : 문서 빈도 값으로, 특정 단어가 여러 데이터에 자주 등장하는 지를 알려주는 지표
* IDF [Inverse Document Frequency] : 이 값에 역수를 취해 구할 수 있으며, 특정 단어가 다른 데이터에 등장하지 않을 수록 값이 커진다는 것을 의미한다
#### 
* TF - IDF 란 이 두 값을 곱해서 사용하므로 어떤 단어가 해당 문서에 자주 등장하지만 다른 문서에는 많이 없는 단어일수록 높은 값을 가지게 된다
-> 따라서 조사나 지시대명사처럼 자주 등장하는 단어는 TF 값은 크지만 IDF 값은 작아지므로 TfidfVectorizer는 CountVectorizer가 가진 문제점을 해결할 수 있다

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
text_data = ['나는 배가 고프다', '내일 점심 뭐먹지', '내일 공부 해야겠다', '점심 먹고 공부 해야지']
tfidf_vectorizer = TfidfVectorizer()

단어사전을 만든 후 단어사전의 목록을 출력하고, 해당 데이터의 한 문장만 객체에 적용해 벡터로 바뀐 값을 출력한다

In [5]:
tfidf_vectorizer.fit(text_data)
print(tfidf_vectorizer.vocabulary_)

sentence = [text_data[3]] # ['점심 먹고 공부 해야지']
print(tfidf_vectorizer.transform(sentence).toarray())

{'나는': 2, '배가': 6, '고프다': 0, '내일': 3, '점심': 7, '뭐먹지': 5, '공부': 1, '해야겠다': 8, '먹고': 4, '해야지': 9}
[[0.         0.43779123 0.         0.         0.55528266 0.
  0.         0.43779123 0.         0.55528266]]
